### ISSUE TITLE
Code cleanup by using Path.move_to_root and Path.rebase_to_root

### ISSUE THREAD

**Issue by davidcassany** [OSInside/kiwi#1281]
## Problem description

With the addition of `Path.move_to_root` and `Path.rebase_to_root` methods some parts of the code are likely to be simplified.

Gonna list here the candidates for refactor:

- [x] kiwi/system/root_bind.move_to_root (it can be removed) #1319
- [x] kiwi/bootloader/install/grub2._get_tool_name #1321
- [x] kiwi/system/setup.setup_plymouth_splash #1321 
- [x] kiwi/defaults.*grub* (some methods to fine the image grub2 location) #1321
